### ISSUE TITLE
Latest `kubebuilder-declarative-pattern` version stuck on endless reconcile loop for guestbook-operator

### ISSUE THREAD

**Issue by asilverman** [kubernetes-sigs/kubebuilder-declarative-pattern#176]
**What happened**:
Following the instructions of the latest version of the [walkthrough](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/tree/master/docs/addon/walkthrough#readme) results in a broken state, the operator enters an endless loop of create/delete of the resources defined in the `channels/packages/guestbook/0.1.0` folder. So the package is never in a `Ready` state.

**What you expected to happen**:
I expected that the package would enter a stable state where it is `Ready`

**How to reproduce it (as minimally and precisely as possible)**:

1) Clone https://github.com/asilverman/guestbook-operator
2) Create a vanilla kind cluster with k8s version 1.12.1 (latest)
From the `guestbook-operator` folder, run (in sequence):
3) `make generate`
4) `make install`
5) `kubectl apply -n kube-system -f config/samples/addons_v1alpha1_guestbook.yaml`
6) `make run`

Inspect the logs of the operator and notice how it enters an endless loop

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
clientVersion:
  buildDate: "2020-08-13T16:12:48Z"
  compiler: gc
  gitCommit: 9f2892aab98fe339f3bd70e3c470144299398ace
  gitTreeState: clean
  gitVersion: v1.18.8
  goVersion: go1.13.15
  major: "1"
  minor: "18"
  platform: linux/amd64
serverVersion:
  buildDate: "2021-05-21T23:01:33Z"
  compiler: gc
  gitCommit: 5e58841cce77d4bc13713ad2b91fa0d961e69192
  gitTreeState: clean
  gitVersion: v1.21.1
  goVersion: go1.16.4
  major: "1"
  minor: "21"
  platform: linux/amd64
```
- OS (e.g: `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
- Kernel (e.g. `uname -a`):
```
Linux OFFICE-DT 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
- Go version (e.g. `go version`): `go version go1.16.5 linux/amd64`

- Others:
