### ISSUE TITLE
Cross namespace pruning is not working as intended 

### ISSUE THREAD

**Issue by JeffLuoo** [kubernetes-sigs/kubebuilder-declarative-pattern#230]
**What happened**:
Using `WithApplyPrune` in the operator doesn't prune the objects in different namespaces.

**What you expected to happen**:
All objects in all namespaces with matching labels will be pruned.

**How to reproduce it (as minimally and precisely as possible)**:
Use the `guestbook` operator [example](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/tree/master/examples/guestbook-operator) and replace the manifest file with 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
``` 
to simplify the deployment.

Deploy the operator in the cluster and wait for the `nginx-deployment` to be deployed. Terminate the operator and update the namespace of the deployment to `default` and then restart the operator. I see that the `nginx-deployment` in the `kube-system` namespace still exists where the `addons.example.org/guestbook: guestbook-sample` is the common labels used by prune.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.23
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 1.17
- Others:
